export const history = [
  {
    id: "287470383365",
    rname: "仮面ライダーセイバー",
    name: "Saber",
    type: "令和",
    pic: "https://jmqs.nilbrains.com/file/drama/poster_saber.jpg",
    years: "2020",
  },
  {
    id: "287688484088",
    rname: "仮面ライダーゼロワン",
    name: "Zero-One",
    type: "令和",
    pic: "https://jmqs.nilbrains.com/file/drama/poster_zeroone.png",
    years: "2019",
  },
  {
    id: "288604156506",
    rname: "仮面ライダージオウ",
    name: "Zi-O",
    type: "平成",
    pic: "https://jmqs.nilbrains.com/file/drama/poster_zio.jpg",
    years: "2018"
  },
  {
    id: "288737475000",
    rname: "仮面ライダービルド",
    name: "Build",
    type: "平成",
    pic: "https://jmqs.nilbrains.com/file/drama/poster_build.jpg",
    years: "2017",
  },
  {
    id: "288953324782",
    rname: "仮面ライダーエグゼイド",
    name: "Ex-Aid",
    type: "平成",
    pic: "https://jmqs.nilbrains.com/file/drama/poster_ex-aid.jpg",
    years: "2016",
  },
  {
    id: "289172770684",
    rname: "仮面ライダーゴースト",
    name: "Ghost",
    type: "平成",
    pic: "https://jmqs.nilbrains.com/file/drama/poster_ghost.jpg",
    years: "2015",
  },
  {
    id: "289218672577",
    rname: "仮面ライダードライブ",
    name: "Drive",
    type: "平成",
    pic: "https://jmqs.nilbrains.com/file/drama/poster_drive.jpg",
    years: "2014",
  },
  {
    id: "289373252784",
    rname: "仮面ライダー鎧武",
    name: "Gaim",
    type: "平成",
    pic: "https://jmqs.nilbrains.com/file/drama/poster_gaim.jpg",
    years: "2013",
  },
  {
    id: "289450653078",
    rname: "仮面ライダーウィザード",
    name: "Wizard",
    type: "平成",
    pic: "https://jmqs.nilbrains.com/file/drama/poster_wizard.jpg",
    years: "2012",
  },
  {
    id: "289497782094",
    rname: "仮面ライダーフォーゼ",
    name: "Fourze",
    type: "平成",
    pic: "https://jmqs.nilbrains.com/file/drama/poster_fourze.jpg",
    years: "2011",
  },
  {
    id: "289541205222",
    rname: "仮面ライダーオーズ/OOO",
    name: "OOO",
    type: "平成",
    pic: "https://jmqs.nilbrains.com/file/drama/poster_ooo.jpg",
    years: "2010",
  },
  {
    id: "289598358497",
    rname: "仮面ライダーW",
    name: "W",
    type: "平成",
    pic: "https://jmqs.nilbrains.com/file/drama/poster_double.jpg",
    years: "2009",
  },
  {
    id: "289654334372",
    rname: "仮面ライダーディケイド",
    name: "Decade",
    type: "平成",
    pic: "https://jmqs.nilbrains.com/file/drama/poster_decade.jpg",
    years: "2009",
  },
  {
    id: "289696865217",
    rname: "仮面ライダーキバ",
    name: "Kiva",
    type: "平成",
    pic: "https://jmqs.nilbrains.com/file/drama/poster_kiva.jpg",
    years: "2008",
  },
  {
    id: "289742152663",
    rname: "仮面ライダー電王",
    name: "电王",
    type: "平成",
    pic: "https://jmqs.nilbrains.com/file/drama/poster_den-o.jpg",
    years: "2007",
  },
  {
    id: "289782351287",
    rname: "仮面ライダーカブト",
    name: "Kabuto",
    type: "平成",
    pic: "https://jmqs.nilbrains.com/file/drama/poster_kabuto.jpg",
    years: "2006",
  },
  {
    id: "289820521264",
    rname: "仮面ライダー響鬼",
    name: "响鬼",
    type: "平成",
    pic: "https://jmqs.nilbrains.com/file/drama/poster_hibiki.jpg",
    years: "2005",
  },
  {
    id: "289871552696",
    rname: "仮面ライダー剣",
    name: "Brade",
    type: "平成",
    pic: "https://jmqs.nilbrains.com/file/drama/poster_brade.jpg",
    years: "2004",
  },
  {
    id: "289915875646",
    rname: "仮面ライダー555",
    name: "Faiz",
    type: "平成",
    pic: "https://jmqs.nilbrains.com/file/drama/poster_555.jpg",
    years: "2003",
  },
  {
    id: "289953254599",
    rname: "仮面ライダー龍騎",
    name: "龙骑",
    type: "平成",
    pic: "https://jmqs.nilbrains.com/file/drama/poster_ryuki.jpg",
    years: "2002",
  },
  {
    id: "290004704341",
    rname: "仮面ライダーアギト",
    name: "AgitΩ",
    type: "平成",
    pic: "https://jmqs.nilbrains.com/file/drama/poster_agito.jpg",
    years: "2001",
  },
  {
    id: "290057548299",
    rname: "仮面ライダークウガ",
    name: "空我",
    type: "平成",
    pic: "https://jmqs.nilbrains.com/file/drama/poster_kuuga.jpg",
    years: "2000",
  },
  {
    id: "013",
    rname: "仮面ライダーJ",
    name: "假面骑士J",
    type: "昭和",
    pic: "https://jmqs.nilbrains.com/file/drama/poster_j.jpg",
    years: "1994",
  },
  {
    id: "012",
    rname: "仮面ライダーZO",
    name: "假面骑士Zo",
    type: "昭和",
    pic: "https://jmqs.nilbrains.com/file/drama/poster_zo.jpg",
    years: "1993",
  },
  {
    id: "011",
    rname: "真・仮面ライダー",
    name: "假面骑士 真",
    type: "昭和",
    pic: "https://jmqs.nilbrains.com/file/drama/poster_shin.jpg",
    years: "1992",
  },
  {
    id: "010",
    rname: "仮面ライダーBLACK RX",
    name: "假面骑士Rx",
    type: "昭和",
    pic: "https://jmqs.nilbrains.com/file/drama/poster_blackrx.jpg",
    years: "1988",
  },
  {
    id: "009",
    rname: "仮面ライダーBLACK",
    name: "假面骑士Black",
    type: "昭和",
    pic: "https://jmqs.nilbrains.com/file/drama/poster_black.jpg",
    years: "1987",
  },
  {
    id: "008",
    rname: "仮面ライダーZX",
    name: "假面骑士ZX",
    type: "昭和",
    pic: "https://jmqs.nilbrains.com/file/drama/poster_zx.jpg",
    years: "1984",
  },
  {
    id: "007",
    rname: "仮面ライダースーパー1",
    name: "Super1",
    type: "昭和",
    pic: "https://jmqs.nilbrains.com/file/drama/poster_super1.jpg",
    years: "1980",
  },
  {
    id: "006",
    rname: "仮面ライダー(新)",
    name: "Skyrider",
    type: "昭和",
    pic: "https://jmqs.nilbrains.com/file/drama/poster_skyrider.jpg",
    years: "1979",
  },
  {
    id: "005",
    rname: "仮面ライダーストロンガー",
    name: "Stronger",
    type: "昭和",
    pic: "https://jmqs.nilbrains.com/file/drama/poster_stronger.jpg",
    years: "1975",
  },
  {
    id: "004",
    rname: "仮面ライダーアマゾン",
    name: "Amazon",
    type: "昭和",
    pic: "https://jmqs.nilbrains.com/file/drama/poster_amazon.jpg",
    years: "1974",
  },
  {
    id: "003",
    rname: "仮面ライダーX",
    name: "假面骑士X",
    type: "昭和",
    pic: "https://jmqs.nilbrains.com/file/drama/poster_x.jpg",
    years: "1973",
  },
  {
    id: "002",
    rname: "仮面ライダーV3",
    name: "假面骑士V3",
    type: "昭和",
    pic: "https://jmqs.nilbrains.com/file/drama/poster_v3.jpg",
    years: "1973",
  },
  {
    id: "001",
    rname: "仮面ライダー",
    name: "假面骑士1号",
    type: "昭和",
    pic: "https://jmqs.nilbrains.com/file/drama/poster_kamen.jpg",
    years: "1971",
  },
];
